glslc ui.vert -o spv/ui.vert.spv
glslc ui.frag -o spv/ui.frag.spv
glslc default.frag -o spv/default.frag.spv
glslc default.vert -o spv/default.vert.spv
glslc shadow.frag -o spv/shadow.frag.spv
glslc shadow.vert -o spv/shadow.vert.spv
glslc terrain.frag -o spv/terrain.frag.spv
glslc terrain.vert -o spv/terrain.vert.spv
glslc terrainWire.frag -o spv/terrainWire.frag.spv
glslc terrainWire.vert -o spv/terrainWire.vert.spv